module Minitest
  module Attributes
    VERSION: String
    TIME_DELTA: Integer

    def assert_attributes: (untyped record, **untyped expected_attributes) -> void
    def assert_hash_attributes: (Hash[untyped, untyped] hash, **untyped expected_attributes) -> void

    private

    def assert_hash_attribute: (Hash[untyped, untyped] hash, Symbol key, untyped expected_value) -> void
    def assert_value: (String label, untyped expected_value, untyped actual_value) -> void
    def value_message: (String label, untyped expected_value, untyped actual_value) -> String
  end
end
